#!/bin/bash

while true
do
  ps -fe|grep 'ssh -N -f -D 0.0.0.0:1080 588161877628e130830000a5@jstardemo-augus.rhcloud.com ps'|grep -v grep > /dev/null 2>&1
  if [ $? -ne 0 ]
  then
    echo `date +'%Y-%m-%d %H:%M:%S'` 'start ssh proxy...'
    ssh -N -f -D 0.0.0.0:1080 588161877628e130830000a5@jstardemo-augus.rhcloud.com ps
  else
    echo `date +'%Y-%m-%d %H:%M:%S'` 'ssh proxy runing...'
  fi
  sleep 1m
done
